# Generated by Django 5.1 on 2024-09-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edan_app', '0002_rename_login_guest_table_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='room_image/')),
                ('video', models.FileField(upload_to='room_video/')),
            ],
        ),
    ]
