# Generated by Django 5.1 on 2024-09-08 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edan_app', '0004_alter_room_table_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_table',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room_table',
            name='video',
        ),
        migrations.AlterField(
            model_name='room_table',
            name='availability',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room_table',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room_table',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='edan_app.room_table')),
            ],
        ),
        migrations.CreateModel(
            name='RoomVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='room_videos/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='edan_app.room_table')),
            ],
        ),
    ]
