# Generated by Django 5.1 on 2024-09-24 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edan_app', '0005_remove_room_table_image_remove_room_table_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_table',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('number_of_guests', models.IntegerField()),
                ('advance_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('CheckedIn', 'Checked In'), ('CheckedOut', 'Checked Out'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edan_app.guest_table')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edan_app.room_table')),
            ],
        ),
    ]
