# Generated by Django 5.1 on 2024-09-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edan_app', '0007_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
    ]
