# Generated by Django 5.1 on 2024-09-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edan_app', '0008_remove_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest_table',
            name='aadhaar_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar_images/'),
        ),
    ]
