# Generated by Django 5.1 on 2024-10-01 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edan_app', '0009_guest_table_aadhaar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edan_app.booking_table')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edan_app.guest_table')),
            ],
        ),
    ]
