# Generated by Django 5.1 on 2024-10-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edan_app', '0010_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='sent_at',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_by',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
