# Generated by Django 5.1 on 2024-10-02 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edan_app', '0012_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('CheckedIn', 'Checked In'), ('CheckedOut', 'Checked Out'), ('Cancelled', 'Cancelled'), ('RefundRequested', 'Refund Requested'), ('Refunded', 'Refunded')], default='Booked', max_length=20),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_refunded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edan_app.booking_table')),
            ],
        ),
    ]
