# Generated by Django 5.1 on 2024-10-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edan_app', '0013_alter_booking_table_status_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
