# Generated by Django 5.1 on 2024-10-26 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edan_app', '0014_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='edan_app.booking_table'),
        ),
    ]
