# Generated by Django 5.1 on 2024-10-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edan_app', '0015_refundrequest_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
