# Generated by Django 5.1 on 2024-10-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edan_app', '0016_refundrequest_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundrequest',
            name='reason',
        ),
    ]
